### ISSUE TITLE
Icons for NavBottom

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/hack-the-budget#20]
Right now, I just have text. I think we will want icons for:

- Home 
- Taxes
- Services
- Report

![](http://dsh.re/5066e)

_related to #13_

**Comment by brainnews** [comment]
@VictoriaODell here are the icons for the tab bar
[PNGs.zip](https://github.com/open-austin/hack-the-budget/files/405067/PNGs.zip)

**Comment by VictoriaODell** [comment]
@brainnews 👌

**Comment by VictoriaODell** [comment]
Can we get them in svgs too @briannews? 
Might be helpful if we want to change the colors or later add hover styling for desktop

**Comment by brainnews** [comment]
SVGs: 
[SVG.zip](https://github.com/open-austin/hack-the-budget/files/405074/SVG.zip)

**Comment by VictoriaODell** [comment]
You're a ⭐  @brainnews
