### ISSUE TITLE
Change Revenue from $911 to $969.2 

### ISSUE THREAD

**Issue by graceatkins** [open-austin/hack-the-budget#22]
The city's revenue from last year was $911 million, so I was just going off that until this year's budget proposal cam out, so the new revenue/General Fund budget is 969.2

**Comment by VictoriaODell** [comment]
Updated in the styling branch. Hope I did the thing right. 
@mateoclarke check the latest styling branch to be sure. 👀

**Comment by mateoclarke** [comment]
u dun gud
