### ISSUE TITLE
Uniform Icons to represent departments and revenue sources

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/hack-the-budget#7]
custom, or just gather from free sources.

**Comment by graceatkins** [comment]
I can work on this? what format should I upload them as?

**Comment by graceatkins** [comment]
https://drive.google.com/folderview?id=0BwevWHqqM3MWcGNnNVNSXzE2OWM&usp=sharing

**Comment by mateoclarke** [comment]
Nice, thanks for gathering those @graceatkins!

I think the ideal format would be SVG. And it could be a fun project for a designer to create some custom icons. But that's not important in the short term. Thanks for getting these so quickly!
